Show test failing with constant string in other file and other package
The linter fails when the constant string is in another file or in
another package:

--- FAIL: TestLinter (20.54s)
    --- FAIL: TestLinter/require-string-key (1.91s)
        analysistest.go:453: a/requirestringkey/example.go:39:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "OtherFileKey1Str" provided with string
        analysistest.go:453: a/requirestringkey/example.go:40:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "otherpkg.KeyStr" provided with string
--- FAIL: TestOptions (14.24s)
    --- FAIL: TestOptions/require-string-key (2.98s)
        analysistest.go:453: a/requirestringkey/example.go:39:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "OtherFileKey1Str" provided with string
        analysistest.go:453: a/requirestringkey/example.go:40:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "otherpkg.KeyStr" provided with string
FAIL
FAIL    github.com/timonwong/loggercheck        34.885s
FAIL