Allow string constants in other file and other package to work (#54)
* Show test failing with constant string in other file and other package

The linter fails when the constant string is in another file or in
another package:

--- FAIL: TestLinter (20.54s)
    --- FAIL: TestLinter/require-string-key (1.91s)
        analysistest.go:453: a/requirestringkey/example.go:39:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "OtherFileKey1Str" provided with string
        analysistest.go:453: a/requirestringkey/example.go:40:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "otherpkg.KeyStr" provided with string
--- FAIL: TestOptions (14.24s)
    --- FAIL: TestOptions/require-string-key (2.98s)
        analysistest.go:453: a/requirestringkey/example.go:39:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "OtherFileKey1Str" provided with string
        analysistest.go:453: a/requirestringkey/example.go:40:28: unexpected diagnostic: logging keys are expected to be inlined constant strings, please replace "otherpkg.KeyStr" provided with string
FAIL
FAIL    github.com/timonwong/loggercheck        34.885s
FAIL

* Update string checking logic to use the type information

This simplifies the checking of keys in structured logging by simply looking at the type
information to determine if it's 1) a string 2) a constant.  With this
change, constants in another file and in a different package now work.

Using TypeAndValue fulfills 1 and 2:
1) Check type is string.
2) Check constant. Per https://pkg.go.dev/go/types#TypeAndValue

> TypeAndValue reports the type and value (for constants) of the
corresponding expression.

So if the value of TypeAndValue is present, then it is a constant.

---------

Co-authored-by: Steve Nguyen <stevehuynguyen@google.com>